### ISSUE TITLE
Metric identifiers

### ISSUE THREAD

**Issue by stefan-it** [huggingface/model_card#1]
Hi,

thanks for setting up this model card template repo 🤗

I would like to adapt some of the new `tags`, so I'm just wondering what "valid" metric identifiers are 🤔

It would be great to have a kind of example list of common identifiers, e.g. a uniform specification of F1-score (like `f_score` or `f1_score`) could be very helpful, so you can add a filter on the model hub page later :)

**Comment by julien-c** [comment]
I think this is clearer in the doc now (https://huggingface.co/docs#what-metadata-can-i-add-to-my-model-card), please re-open if that's not the case
