### ISSUE TITLE
Needs updating

### ISSUE THREAD

**Issue by mmitchellai** [huggingface/model_card#5]
Currently reads that the canonical documentation for model cards is at https://huggingface.co/docs; but that is no longer a place where there is a clear link to documentation. I think this part of the repo could serve as the canonical source instead.

**Comment by julien-c** [comment]
yes, in the short term should we link to https://huggingface.co/docs/hub/model-repos#what-are-model-cards-and-why-are-they-useful and/or the "spec" for the metadata part of the model card at https://github.com/huggingface/huggingface_hub/blame/main/modelcard.md?

also cc @osanseviero

**Comment by elishowk** [comment]
I feel this repository duplicates informations with the [more up to date documentation](https://huggingface.co/docs/hub/model-repos#what-are-model-cards-and-why-are-they-useful) and [modelcard.md spec in the huggingface_hub](https://github.com/huggingface/huggingface_hub/blame/main/modelcard.md)

But I'm not sure how much, if any, this repository is a dependency to other tools ?

**Comment by julien-c** [comment]
Yes, my feeling is that we should archive and deprecate this repo and move its content to `huggingface_hub`, what do you all think?

**Comment by osanseviero** [comment]
@mmitchellai what do you think? It would be great if we could move the excellent work done here to our [official documentation](https://huggingface.co/docs/hub/model-repos#what-are-model-cards-and-why-are-they-useful) so it can have more visibility and impact.
